config/routes.rb
Rails.application.routes.draw do
  
  root 'categories#index'
  
  devise_for :users
  
  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :baskets
  
  namespace :admin do
    resources :products
    resources :categories
  end
end

app/models/basket.rb
class Basket < ActiveRecord::Base
  has_and_belongs_to_many :products
  has_one :busket_item
  belongs_to :busket_item
  
  validates :total_price, presence: true, numericality: { greater_than: 0 }
end

app/models/busket_item.rb
class BusketItem < ActiveRecord::Base
  has_one :product
  has_many :baskets
  belongs_to :product
  belongs_to :basket
  
  validates :quantity, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  belongs_to :user
  
  validates :title, presence: true
  
  mount_uploader :picture, PictureUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_and_belongs_to_many :baskets
  has_one :busket_item
  belongs_to :busket_item
  
  validates :title, presence: true
  validates :sku, presence: true, uniqueness: true
  validates :price, numericality: { greater_than: 0 }
  
  mount_uploader :picture, PictureUploader
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Declaration of relationships
  has_many :products, dependent: :destroy
  has_many :categories, dependent: :destroy
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  # GET /products
  def index
    @categories = Category.all
  end
  
  # GET /products/1
  def show
  end
  
  # GET /products/new
  def new
    @category = Category.new
    @product = Product.new
  end
  
  # GET /products/1/edit
  def edit
    @products = Product.all
  end
  
  # POST /products
  def create
    @category = Category.new(category_params)
    
    if @category.save
      redirect_to admin_category_path(@category), notice: 'Category was successfully created.'
    else
      render :new
    end
  end
  
  # PATCH/PUT /products/1
  def update
    if @category.update(category_params)
      redirect_to admin_category_path(@category), notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end
  
  # DELETE /products/1
  def destroy
    @category.destroy
    redirect_to admin_categories_path, notice: 'Category was successfully destroyed.'
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :product_id, :picture)
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  # GET /products 
  def index
    @products = Product.all
    @categories = Category.all
  end
  
  # GET /products/1
  def show
  end
  
  # GET /products/new
  def new
    @product = Product.new
  end
  
  # GET /products/1/edit
  def edit
  end
  
  # POST /productss
  def create
    @product = Product.new(product_params)   
    if @product.save
      redirect_to admin_product_path(@product), notice: 'Product was successfully created.'
    else
      render :new
    end
  end
  
  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end
  
  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to admin_products_path, notice: 'Product was successfully destroyed.'
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :sku, :description, :price, :category_id, :picture)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  def index
    @baskets = Basket.all
    @products = Product.all
  end
  
  # GET /products/1
  def show
    @basket = Basket.find(params[:id])
  end
  
  def edit
    @products = Product.all
  end
  
  # PATCH/PUT /products/1
  def update
    if @basket.update(basket_params)
      redirect_to basket_path(@basket), notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end
  
  # DELETE /products/1
  def destroy
    @basket.destroy
    redirect_to basket_path, notice: 'Product was successfully destroyed.'
  end
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:basket).permit(:total_price, :product_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /products
  def index
    @categories = Category.all
    @products = Product.all
  end
  
  # GET /products/1
  def show
    @category = Category.find(params[:id])
  end
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :product_id, :picture)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  def index
    @products = Product.all
    @categories = Category.all
  end
  
  # GET /products/1
  def show
    @product = Product.find(params[:id])
  end
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :sku, :description, :price, :category_id, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/categories/_form.slim
= form_for [:admin, @category] do |f|
  - if @category.errors.any?
    #error_explanation
      h2
        = pluralize(@category.errors.count, "error")
        | prohibited this category from being saved:
      ul
        - @category.errors.full_messages.each do |message|
          li = message
  
  = f.file_field :picture
  
  div
    = f.label :title
    br
    = f.text_field :title
  
  div.actions
    = f.submit

app/views/admin/categories/edit.slim
h1 Editing Category

= render 'form'

= link_to 'Show', admin_category_path(@category)
|  | 
= link_to 'Back', admin_categories_path

app/views/admin/categories/index.slim
p#notice
  = notice

h1 Listing Categories

table border="1"
  thead
    tr
      th ID
      th Title
      th Products
      th Picture
      th colspan="3" Actions
  tbody
    - @categories.each do |category|
      tr
        td
          = category.id
        td
          = category.title
        td
          = category.products.count
        td
          - if category.picture.length > 0
            = image_tag category.picture.thumb
          - else
            | No picture
        td
          = link_to 'Show', admin_category_path(category)
        td
          = link_to 'Edit', edit_admin_category_path(category)
        td
          = link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: 'Подумай двійчі!!!!' }

br

= link_to 'New category', new_admin_category_path
br
= link_to 'All products', admin_products_path

app/views/admin/categories/new.slim
h1 New category

= render 'form'
br

= link_to 'Back', admin_categories_path

app/views/admin/categories/show.slim
p#notice
  = notice

h1 Listing Categories

table border="1"
  thead
    tr
      th ID
      th Title
      th Show
      th Edit
      th Delete
      th Products
      th Picture
  tbody
    tr
      td
       = @category.id
      td
       = @category.title
      td
       = link_to 'Show', admin_category_path(@category)
      td
       = link_to 'Edit', edit_admin_category_path(@category)
      td
       = link_to 'Delete', admin_category_path(@category), method: :delete, data: { confirm: 'Подумай двійчі!!!!' }
      td
       = @category.products.count
      td
        - if @category.picture.length
          = image_tag @category.picture.thumb
        - else
          | No picture

div.actions
  = link_to 'Back', admin_categories_path

app/views/admin/products/_form.slim
= form_for [:admin, @product] do |f| 
  - if @product.errors.any?
    div#error_explanation
      h2 = pluralize(@product.errors.count, "error") 
      | prohibited this product from being saved:
      ul
        - @product.errors.full_messages.each do |message| 
          li = message
  
  div
    = f.file_field :picture
  
  div
     = f.label :title
     br
     = f.text_field :title
  
  div
    = f.label :sku
    br
    = f.text_field :sku
  
  div
     = f.label :description
     br
     = f.text_field :description
   
  div
    = f.label :price
    br
	=f.number_field :price, step: 0.01
  
  div
    = f.label :category 
    br
    = f.collection_select :category_id, Category.all, :id, :title, { include_blank: true }
  
  div.actions
    = f.submit  

app/views/admin/products/edit.slim
h1 Editing Product

= render 'form'

= link_to 'Show', @product
= link_to 'Back', admin_products_path

app/views/admin/products/index.slim
.row
  .col-md-6.col-md-offset-3
    p#notice
      = notice
    .col-md-7.col-md-offset-3 
      h1 Listing Products
    table.table.table-striped border='5'
      thead
        tr
          th ID
          th Title
          th SKU
          th Description
          th Price
          th Show
          th Edit
          th Destroy
          th Category
          th Picture
      tbody  class="table table-striped"
        - @products.each do |product|
          tr
            td
              = product.id
            td
              = product.title
            td
              = product.sku
            td
              = product.description
            td
              = product.price
            td
              = link_to 'Show', admin_product_path(product), class: "btn btn-info"
            td
              = link_to 'Edit', edit_admin_product_path(product), class: "btn btn-warning"
            td
              = link_to 'Delete', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
            td
              - if product.category
                = link_to product.category.title, admin_category_path(product.category)
              - else
                | No category
            td
              - if product.picture.length > 0 
                = image_tag product.picture.thumb
              - else
                | No picture

  br
  = link_to 'New Product', new_admin_product_path, class: 'btn btn-success'
  br
  = link_to 'All categories', admin_categories_path

app/views/admin/products/new.slim
h1 New Product

= render 'form'

= link_to 'Back', admin_products_path

app/views/admin/products/show.slim
p#notice
= notice
h1 Listing Products
table border='5'
  thead
    tr
      th ID
      th Title
      th SKU
      th Description
      th Price
      th Show
      th Edit
      th Destroy
      th Category
      th Picture
  tbody
    tr
      td = @product.id
      td = @product.title
      td = @product.sku
      td = @product.description
      td = @product.price
      td = link_to 'Show', admin_product_path(@product)
      td = link_to 'Edit', edit_admin_product_path(@product)
      td = link_to 'Delete', admin_product_path(@product), method: :delete, data: { confirm: 'Are you sure?' }
      td
        - if @product.category
          = link_to @product.category.title, admin_category_path(@product.category)
        - else
          | No category
      td
        - if @product.picture.length > 0
          = image_tag @product.picture.thumb
        - else
          | No picture

.btn.btn-success
  = link_to 'Back', admin_products_path

app/views/baskets/_form.slim
= form_for [@basket] do |f| 
  - if @basket.errors.any?
    div#error_explanation
      h2 = pluralize(@basket.errors.count, "error") 
      | prohibited this product from being saved:
      ul
        - @basket.errors.full_messages.each do |message| 
          li = message
  
  div
    = f.file_field :picture
  
  div
     = f.label :title
     br
     = f.text_field :title
  
  div
    = f.label :sku
    br
    = f.text_field :sku
  
  div
     = f.label :description
     br
     = f.text_field :description
   
  div
    = f.label :price
    br
	=f.number_field :price, step: 0.01
  
  div
    = f.label :category 
    br
    = f.collection_select :category_id, Category.all, :id, :title, { include_blank: true }
  
  div.actions
    = f.submit  

app/views/baskets/index.slim
.row
  .col-md-6.col-md-offset-3
    p#notice
      = notice
    .col-md-7.col-md-offset-3 
      h1 My basket
    table.table.table-striped border='5'
      thead
        tr
          th ID
          th Title
          th SKU
          th Description
          th Price
          th Show
          th Edit
          th Destroy
          th Category
          th Picture
          th Quantity
      tbody  class="table table-striped"
        - @baskets.each do |basket|
          tr
            td
              = basket.product.id
            td
              = basket.product.title
            td
              = basket.product.sku
            td
              = basket.product.description
            td
              = basket.product.price
            td
              = link_to 'Show', basket_path(basket), class: "btn btn-info"
            td
              = link_to 'Edit', basket_product_path(basket), class: "btn btn-warning"
            td
              = link_to 'Delete', basket_path(basket), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
            td
              - if basket.product.category
                = link_to basket.product.category.title, category_path(basket.product.category)
              - else
                | No category
            td
              - if basket.product.picture.length > 0 
                = image_tag basket.product.picture.thumb
              - else
                | No picture
            td = basket.products.count

  br
  = link_to 'All products', products_path, class: 'btn btn-success'
  br
  = link_to 'All categories', categories_path

app/views/categories/index.slim
p#notice
  = notice 

h1 Listing Categories

table border="1"
  thead
    tr
      th ID
      th Title
      th Products
      th Picture
      th Show
  tbody
    - @categories.each do |category|
      tr
        td = category.id
        td = category.title
        td = category.products.count
        td
          - if category.picture.length > 0
            = image_tag category.picture.thumb
          - else
           | No picture
        td
          = link_to 'Show', category_path(category)
           
br
= link_to 'All products', products_path
br
= link_to 'If you admin', admin_categories_path

app/views/categories/show.slim
p#notice
= notice
table border="2"
  thead
    tr
      th Title
      th Count of Products
      th Picture
  tbody
    tr
      td = @category.title
      td = @category.products.count
      td
        - if @category.picture.length > 0
          = image_tag @category.picture.thumb
        - else
          | No picture

div.actions
  = link_to 'Back', categories_path

app/views/layouts/application.slim
doctype html
html
  head
    title Store
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    
  body
    .row.col-md-6.col-md-offset-3
      - if user_signed_in?
        = link_to 'Sign Out', destroy_user_session_path, method: :delete
      - else
        = link_to 'Sign In', new_user_session_path
    br
    
    = yield

app/views/products/index.slim
p#notice 
  = notice

h1 Listing Products

table border='5'
  thead
    tr
      th ID
      th Title
      th SKU
      th Description
      th Price
      th Category
      th Picture
  tbody
    - @products.each do |product|
      tr
        td = product.id
        td = product.title
        td = product.sku
        td = product.description
        td = product.price
        td
          - if product.category
            = link_to product.category.title, category_path(product.category)
          - else
            | No category
        td
          - if product.picture.length > 0
            = image_tag product.picture.thumb
          - else
            | No picture
            
            
br
= link_to 'All categories', categories_path

app/views/products/show.slim
p#notice
  = notice

table border="2"
  thead
    tr
      th Title
      th SKU
      th Description
      th Price
      th Category
      th Picture
  tbody
    tr
      td = @product.title
      td = @product.sku
      td = @product.description %></td>
      td = @product.price
      td
        - if @product.category
          = @product.category.title
        - else
         | No Category
      td
          - if @product.picture.length > 0
            = image_tag @product.picture.thumb
          - else
            | No picture

div.actions
  = link_to 'Back', products_path